/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	tmcv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tmc/v1alpha1"
	applyconfigurationtmcv1alpha1 "github.com/kcp-dev/kcp/pkg/client/tmc/applyconfiguration/tmc/v1alpha1"
	scheme "github.com/kcp-dev/kcp/pkg/client/tmc/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClusterRegistrationsGetter has a method to return a ClusterRegistrationInterface.
// A group's client should implement this interface.
type ClusterRegistrationsGetter interface {
	ClusterRegistrations() ClusterRegistrationInterface
}

// ClusterRegistrationInterface has methods to work with ClusterRegistration resources.
type ClusterRegistrationInterface interface {
	Create(ctx context.Context, clusterRegistration *tmcv1alpha1.ClusterRegistration, opts v1.CreateOptions) (*tmcv1alpha1.ClusterRegistration, error)
	Update(ctx context.Context, clusterRegistration *tmcv1alpha1.ClusterRegistration, opts v1.UpdateOptions) (*tmcv1alpha1.ClusterRegistration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, clusterRegistration *tmcv1alpha1.ClusterRegistration, opts v1.UpdateOptions) (*tmcv1alpha1.ClusterRegistration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*tmcv1alpha1.ClusterRegistration, error)
	List(ctx context.Context, opts v1.ListOptions) (*tmcv1alpha1.ClusterRegistrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *tmcv1alpha1.ClusterRegistration, err error)
	Apply(ctx context.Context, clusterRegistration *applyconfigurationtmcv1alpha1.ClusterRegistrationApplyConfiguration, opts v1.ApplyOptions) (result *tmcv1alpha1.ClusterRegistration, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, clusterRegistration *applyconfigurationtmcv1alpha1.ClusterRegistrationApplyConfiguration, opts v1.ApplyOptions) (result *tmcv1alpha1.ClusterRegistration, err error)
	ClusterRegistrationExpansion
}

// clusterRegistrations implements ClusterRegistrationInterface
type clusterRegistrations struct {
	*gentype.ClientWithListAndApply[*tmcv1alpha1.ClusterRegistration, *tmcv1alpha1.ClusterRegistrationList, *applyconfigurationtmcv1alpha1.ClusterRegistrationApplyConfiguration]
}

// newClusterRegistrations returns a ClusterRegistrations
func newClusterRegistrations(c *TmcV1alpha1Client) *clusterRegistrations {
	return &clusterRegistrations{
		gentype.NewClientWithListAndApply[*tmcv1alpha1.ClusterRegistration, *tmcv1alpha1.ClusterRegistrationList, *applyconfigurationtmcv1alpha1.ClusterRegistrationApplyConfiguration](
			"clusterregistrations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *tmcv1alpha1.ClusterRegistration { return &tmcv1alpha1.ClusterRegistration{} },
			func() *tmcv1alpha1.ClusterRegistrationList { return &tmcv1alpha1.ClusterRegistrationList{} },
		),
	}
}
