/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	tmcv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tmc/v1alpha1"
	applyconfigurationtmcv1alpha1 "github.com/kcp-dev/kcp/pkg/client/tmc/applyconfiguration/tmc/v1alpha1"
	scheme "github.com/kcp-dev/kcp/pkg/client/tmc/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WorkloadPlacementsGetter has a method to return a WorkloadPlacementInterface.
// A group's client should implement this interface.
type WorkloadPlacementsGetter interface {
	WorkloadPlacements(namespace string) WorkloadPlacementInterface
}

// WorkloadPlacementInterface has methods to work with WorkloadPlacement resources.
type WorkloadPlacementInterface interface {
	Create(ctx context.Context, workloadPlacement *tmcv1alpha1.WorkloadPlacement, opts v1.CreateOptions) (*tmcv1alpha1.WorkloadPlacement, error)
	Update(ctx context.Context, workloadPlacement *tmcv1alpha1.WorkloadPlacement, opts v1.UpdateOptions) (*tmcv1alpha1.WorkloadPlacement, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workloadPlacement *tmcv1alpha1.WorkloadPlacement, opts v1.UpdateOptions) (*tmcv1alpha1.WorkloadPlacement, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*tmcv1alpha1.WorkloadPlacement, error)
	List(ctx context.Context, opts v1.ListOptions) (*tmcv1alpha1.WorkloadPlacementList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *tmcv1alpha1.WorkloadPlacement, err error)
	Apply(ctx context.Context, workloadPlacement *applyconfigurationtmcv1alpha1.WorkloadPlacementApplyConfiguration, opts v1.ApplyOptions) (result *tmcv1alpha1.WorkloadPlacement, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, workloadPlacement *applyconfigurationtmcv1alpha1.WorkloadPlacementApplyConfiguration, opts v1.ApplyOptions) (result *tmcv1alpha1.WorkloadPlacement, err error)
	WorkloadPlacementExpansion
}

// workloadPlacements implements WorkloadPlacementInterface
type workloadPlacements struct {
	*gentype.ClientWithListAndApply[*tmcv1alpha1.WorkloadPlacement, *tmcv1alpha1.WorkloadPlacementList, *applyconfigurationtmcv1alpha1.WorkloadPlacementApplyConfiguration]
}

// newWorkloadPlacements returns a WorkloadPlacements
func newWorkloadPlacements(c *TmcV1alpha1Client, namespace string) *workloadPlacements {
	return &workloadPlacements{
		gentype.NewClientWithListAndApply[*tmcv1alpha1.WorkloadPlacement, *tmcv1alpha1.WorkloadPlacementList, *applyconfigurationtmcv1alpha1.WorkloadPlacementApplyConfiguration](
			"workloadplacements",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *tmcv1alpha1.WorkloadPlacement { return &tmcv1alpha1.WorkloadPlacement{} },
			func() *tmcv1alpha1.WorkloadPlacementList { return &tmcv1alpha1.WorkloadPlacementList{} },
		),
	}
}
