/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	workloadv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/workload/v1alpha1"
	applyconfigurationworkloadv1alpha1 "github.com/kcp-dev/kcp/sdk/client/applyconfiguration/workload/v1alpha1"
	scheme "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/scheme"
)

// WorkloadStatusAggregationsGetter has a method to return a WorkloadStatusAggregationInterface.
// A group's client should implement this interface.
type WorkloadStatusAggregationsGetter interface {
	WorkloadStatusAggregations() WorkloadStatusAggregationInterface
}

// WorkloadStatusAggregationInterface has methods to work with WorkloadStatusAggregation resources.
type WorkloadStatusAggregationInterface interface {
	Create(ctx context.Context, workloadStatusAggregation *workloadv1alpha1.WorkloadStatusAggregation, opts v1.CreateOptions) (*workloadv1alpha1.WorkloadStatusAggregation, error)
	Update(ctx context.Context, workloadStatusAggregation *workloadv1alpha1.WorkloadStatusAggregation, opts v1.UpdateOptions) (*workloadv1alpha1.WorkloadStatusAggregation, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workloadStatusAggregation *workloadv1alpha1.WorkloadStatusAggregation, opts v1.UpdateOptions) (*workloadv1alpha1.WorkloadStatusAggregation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadv1alpha1.WorkloadStatusAggregation, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadv1alpha1.WorkloadStatusAggregationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadv1alpha1.WorkloadStatusAggregation, err error)
	Apply(ctx context.Context, workloadStatusAggregation *applyconfigurationworkloadv1alpha1.WorkloadStatusAggregationApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.WorkloadStatusAggregation, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, workloadStatusAggregation *applyconfigurationworkloadv1alpha1.WorkloadStatusAggregationApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.WorkloadStatusAggregation, err error)
	WorkloadStatusAggregationExpansion
}

// workloadStatusAggregations implements WorkloadStatusAggregationInterface
type workloadStatusAggregations struct {
	*gentype.ClientWithListAndApply[*workloadv1alpha1.WorkloadStatusAggregation, *workloadv1alpha1.WorkloadStatusAggregationList, *applyconfigurationworkloadv1alpha1.WorkloadStatusAggregationApplyConfiguration]
}

// newWorkloadStatusAggregations returns a WorkloadStatusAggregations
func newWorkloadStatusAggregations(c *WorkloadV1alpha1Client) *workloadStatusAggregations {
	return &workloadStatusAggregations{
		gentype.NewClientWithListAndApply[*workloadv1alpha1.WorkloadStatusAggregation, *workloadv1alpha1.WorkloadStatusAggregationList, *applyconfigurationworkloadv1alpha1.WorkloadStatusAggregationApplyConfiguration](
			"workloadstatusaggregations",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *workloadv1alpha1.WorkloadStatusAggregation {
				return &workloadv1alpha1.WorkloadStatusAggregation{}
			},
			func() *workloadv1alpha1.WorkloadStatusAggregationList {
				return &workloadv1alpha1.WorkloadStatusAggregationList{}
			},
		),
	}
}
