{{- if and .Values.syncer.kcp.kubeconfig (not .Values.syncer.kcp.kubeconfigSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kcp-syncer.fullname" . }}-kcp-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcp-syncer.labels" . | nindent 4 }}
    component: kcp-kubeconfig
type: Opaque
data:
  kubeconfig: {{ .Values.syncer.kcp.kubeconfig | b64enc }}
---
{{- end }}

{{- if and .Values.syncer.cluster.kubeconfig (not .Values.syncer.cluster.kubeconfigSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kcp-syncer.fullname" . }}-cluster-kubeconfig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcp-syncer.labels" . | nindent 4 }}
    component: cluster-kubeconfig
type: Opaque
data:
  kubeconfig: {{ .Values.syncer.cluster.kubeconfig | b64enc }}
{{- end }}