{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kcp-syncer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcp-syncer.labels" . | nindent 4 }}
    component: syncer
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.ports.metrics }}
    targetPort: {{ .Values.service.ports.metrics }}
    protocol: TCP
    name: metrics
  - port: {{ .Values.service.ports.health }}
    targetPort: {{ .Values.service.ports.health }}
    protocol: TCP
    name: health
  selector:
    {{- include "kcp-syncer.selectorLabels" . | nindent 4 }}
    component: syncer
{{- end }}