/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	tmcv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tmc/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/kcp/pkg/client/tmc/applyconfiguration/tmc/v1alpha1"
	typedkcptmcv1alpha1 "github.com/kcp-dev/kcp/pkg/client/tmc/clientset/versioned/cluster/typed/tmc/v1alpha1"
	typedtmcv1alpha1 "github.com/kcp-dev/kcp/pkg/client/tmc/clientset/versioned/typed/tmc/v1alpha1"
	"github.com/kcp-dev/logicalcluster/v3"
)

// workloadPlacementClusterClient implements WorkloadPlacementClusterInterface
type workloadPlacementClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*tmcv1alpha1.WorkloadPlacement, *tmcv1alpha1.WorkloadPlacementList]
	Fake *kcptesting.Fake
}

func newFakeWorkloadPlacementClusterClient(fake *TmcV1alpha1ClusterClient) typedkcptmcv1alpha1.WorkloadPlacementClusterInterface {
	return &workloadPlacementClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*tmcv1alpha1.WorkloadPlacement, *tmcv1alpha1.WorkloadPlacementList](
			fake.Fake,
			tmcv1alpha1.SchemeGroupVersion.WithResource("workloadplacements"),
			tmcv1alpha1.SchemeGroupVersion.WithKind("WorkloadPlacement"),
			func() *tmcv1alpha1.WorkloadPlacement { return &tmcv1alpha1.WorkloadPlacement{} },
			func() *tmcv1alpha1.WorkloadPlacementList { return &tmcv1alpha1.WorkloadPlacementList{} },
			func(dst, src *tmcv1alpha1.WorkloadPlacementList) { dst.ListMeta = src.ListMeta },
			func(list *tmcv1alpha1.WorkloadPlacementList) []*tmcv1alpha1.WorkloadPlacement {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *tmcv1alpha1.WorkloadPlacementList, items []*tmcv1alpha1.WorkloadPlacement) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *workloadPlacementClusterClient) Cluster(cluster logicalcluster.Path) typedkcptmcv1alpha1.WorkloadPlacementsNamespacer {
	return &workloadPlacementNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type workloadPlacementNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *workloadPlacementNamespacer) Namespace(namespace string) typedtmcv1alpha1.WorkloadPlacementInterface {
	return newFakeWorkloadPlacementClient(n.Fake, namespace, n.ClusterPath)
}

// workloadPlacementScopedClient implements WorkloadPlacementInterface
type workloadPlacementScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*tmcv1alpha1.WorkloadPlacement, *tmcv1alpha1.WorkloadPlacementList, *kcpv1alpha1.WorkloadPlacementApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeWorkloadPlacementClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typedtmcv1alpha1.WorkloadPlacementInterface {
	return &workloadPlacementScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*tmcv1alpha1.WorkloadPlacement, *tmcv1alpha1.WorkloadPlacementList, *kcpv1alpha1.WorkloadPlacementApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			tmcv1alpha1.SchemeGroupVersion.WithResource("workloadplacements"),
			tmcv1alpha1.SchemeGroupVersion.WithKind("WorkloadPlacement"),
			func() *tmcv1alpha1.WorkloadPlacement { return &tmcv1alpha1.WorkloadPlacement{} },
			func() *tmcv1alpha1.WorkloadPlacementList { return &tmcv1alpha1.WorkloadPlacementList{} },
			func(dst, src *tmcv1alpha1.WorkloadPlacementList) { dst.ListMeta = src.ListMeta },
			func(list *tmcv1alpha1.WorkloadPlacementList) []*tmcv1alpha1.WorkloadPlacement {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *tmcv1alpha1.WorkloadPlacementList, items []*tmcv1alpha1.WorkloadPlacement) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
