kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: helm-kcp
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "node-type=kcp-host,demo=helm-deployment"
  extraPortMappings:
  - containerPort: 6443
    hostPort: 38443
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
