apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v250804-755cf794.resourceexports.workload.kcp.io
spec:
  group: workload.kcp.io
  names:
    categories:
    - kcp
    kind: ResourceExport
    listKind: ResourceExportList
    plural: resourceexports
    shortNames:
    - re
    singular: resourceexport
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Target cluster
      jsonPath: .spec.target.clusters[0]
      name: Target
      type: string
    - description: Resource type
      jsonPath: .spec.resource.resource
      name: Resource
      type: string
    - description: Resource namespace
      jsonPath: .spec.resource.namespace
      name: Namespace
      type: string
    - description: Resource name
      jsonPath: .spec.resource.name
      name: Name
      type: string
    - description: Ready condition status
      jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      description: |-
        ResourceExport represents a resource that should be exported from KCP
        to one or more SyncTargets for execution.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: Spec defines the desired state of the ResourceExport
          properties:
            conflictResolution:
              allOf:
              - enum:
                - UseSource
                - UseTarget
                - Error
              - enum:
                - UseSource
                - UseTarget
                - Error
              default: UseSource
              description: ConflictResolution defines how conflicts should be handled
              type: string
            resource:
              description: Resource specifies the resource to be exported
              properties:
                group:
                  description: Group is the API group of the resource
                  type: string
                name:
                  description: Name is the name of the resource
                  type: string
                namespace:
                  description: Namespace is the namespace of the resource (if namespaced)
                  type: string
                resource:
                  description: Resource is the resource type (plural name)
                  type: string
                version:
                  description: Version is the API version of the resource
                  type: string
              required:
              - name
              - resource
              - version
              type: object
            target:
              description: Target specifies where the resource should be exported
              properties:
                clusters:
                  description: Clusters lists the target clusters for export
                  items:
                    type: string
                  type: array
                labelSelector:
                  description: LabelSelector selects clusters based on labels
                  properties:
                    matchExpressions:
                      description: matchExpressions is a list of label selector requirements.
                        The requirements are ANDed.
                      items:
                        description: |-
                          A label selector requirement is a selector that contains values, a key, and an operator that
                          relates the key and values.
                        properties:
                          key:
                            description: key is the label key that the selector applies
                              to.
                            type: string
                          operator:
                            description: |-
                              operator represents a key's relationship to a set of values.
                              Valid operators are In, NotIn, Exists and DoesNotExist.
                            type: string
                          values:
                            description: |-
                              values is an array of string values. If the operator is In or NotIn,
                              the values array must be non-empty. If the operator is Exists or DoesNotExist,
                              the values array must be empty. This array is replaced during a strategic
                              merge patch.
                            items:
                              type: string
                            type: array
                            x-kubernetes-list-type: atomic
                        required:
                        - key
                        - operator
                        type: object
                      type: array
                      x-kubernetes-list-type: atomic
                    matchLabels:
                      additionalProperties:
                        type: string
                      description: |-
                        matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                        map is equivalent to an element of matchExpressions, whose key field is "key", the
                        operator is "In", and the values array contains only "value". The requirements are ANDed.
                      type: object
                  type: object
                  x-kubernetes-map-type: atomic
                locationSelector:
                  description: LocationSelector selects clusters based on location
                  properties:
                    labelSelector:
                      description: LabelSelector selects locations based on labels
                      properties:
                        matchExpressions:
                          description: matchExpressions is a list of label selector
                            requirements. The requirements are ANDed.
                          items:
                            description: |-
                              A label selector requirement is a selector that contains values, a key, and an operator that
                              relates the key and values.
                            properties:
                              key:
                                description: key is the label key that the selector
                                  applies to.
                                type: string
                              operator:
                                description: |-
                                  operator represents a key's relationship to a set of values.
                                  Valid operators are In, NotIn, Exists and DoesNotExist.
                                type: string
                              values:
                                description: |-
                                  values is an array of string values. If the operator is In or NotIn,
                                  the values array must be non-empty. If the operator is Exists or DoesNotExist,
                                  the values array must be empty. This array is replaced during a strategic
                                  merge patch.
                                items:
                                  type: string
                                type: array
                                x-kubernetes-list-type: atomic
                            required:
                            - key
                            - operator
                            type: object
                          type: array
                          x-kubernetes-list-type: atomic
                        matchLabels:
                          additionalProperties:
                            type: string
                          description: |-
                            matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels
                            map is equivalent to an element of matchExpressions, whose key field is "key", the
                            operator is "In", and the values array contains only "value". The requirements are ANDed.
                          type: object
                      type: object
                      x-kubernetes-map-type: atomic
                    path:
                      description: Path specifies the location path pattern to match
                      type: string
                  type: object
              type: object
          required:
          - resource
          - target
          type: object
        status:
          description: Status represents the current state of the ResourceExport
          properties:
            conditions:
              description: Conditions represent the latest available observations
                of the export's current state
              items:
                description: Condition defines an observation of a object operational
                  state.
                properties:
                  lastTransitionTime:
                    description: |-
                      Last time the condition transitioned from one status to another.
                      This should be when the underlying condition changed. If that is not known, then using the time when
                      the API field changed is acceptable.
                    format: date-time
                    type: string
                  message:
                    description: |-
                      A human readable message indicating details about the transition.
                      This field may be empty.
                    type: string
                  reason:
                    description: |-
                      The reason for the condition's last transition in CamelCase.
                      The specific API may choose whether or not this field is considered a guaranteed API.
                      This field may not be empty.
                    type: string
                  severity:
                    description: |-
                      Severity provides an explicit classification of Reason code, so the users or machines can immediately
                      understand the current situation and act accordingly.
                      The Severity field MUST be set only when Status=False.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: |-
                      Type of condition in CamelCase or in foo.example.com/CamelCase.
                      Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
                      can be useful (see .node.status.conditions), the ability to deconflict is important.
                    type: string
                required:
                - lastTransitionTime
                - status
                - type
                type: object
              type: array
            exportedClusters:
              description: ExportedClusters tracks which clusters the resource has
                been exported to
              items:
                description: ClusterExportStatus tracks export status for a specific
                  cluster
                properties:
                  cluster:
                    description: Cluster is the name of the target cluster
                    type: string
                  error:
                    description: Error records any export errors for this cluster
                    type: string
                  exported:
                    description: Exported indicates if the export was successful
                    type: boolean
                  lastExportTime:
                    description: LastExportTime records the last export time for this
                      cluster
                    format: date-time
                    type: string
                required:
                - cluster
                - exported
                type: object
              type: array
            lastExportTime:
              description: LastExportTime is when the resource was last exported
              format: date-time
              type: string
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
