apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v250805-30fc9e6d.clusterregistrations.tmc.kcp.io
spec:
  group: tmc.kcp.io
  names:
    kind: ClusterRegistration
    listKind: ClusterRegistrationList
    plural: clusterregistrations
    singular: clusterregistration
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      description: ClusterRegistration represents a physical cluster registered with
        the TMC for workload management.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: ClusterRegistrationSpec holds the desired state of the ClusterRegistration.
          properties:
            clusterEndpoint:
              description: ClusterEndpoint defines how to connect to the cluster
              properties:
                caBundle:
                  description: CABundle contains the certificate authority bundle
                    for the cluster
                  format: byte
                  type: string
                serverURL:
                  description: ServerURL is the URL of the Kubernetes API server
                  format: uri
                  type: string
              required:
              - serverURL
              type: object
            location:
              description: Location specifies the geographical location of the cluster
              type: string
          required:
          - clusterEndpoint
          - location
          type: object
        status:
          description: ClusterRegistrationStatus communicates the observed state of
            the ClusterRegistration.
          properties:
            conditions:
              description: Conditions represent the latest available observations
                of the cluster's state
              items:
                description: Condition defines an observation of a object operational
                  state.
                properties:
                  lastTransitionTime:
                    description: |-
                      Last time the condition transitioned from one status to another.
                      This should be when the underlying condition changed. If that is not known, then using the time when
                      the API field changed is acceptable.
                    format: date-time
                    type: string
                  message:
                    description: |-
                      A human readable message indicating details about the transition.
                      This field may be empty.
                    type: string
                  reason:
                    description: |-
                      The reason for the condition's last transition in CamelCase.
                      The specific API may choose whether or not this field is considered a guaranteed API.
                      This field may not be empty.
                    type: string
                  severity:
                    description: |-
                      Severity provides an explicit classification of Reason code, so the users or machines can immediately
                      understand the current situation and act accordingly.
                      The Severity field MUST be set only when Status=False.
                    type: string
                  status:
                    description: Status of the condition, one of True, False, Unknown.
                    type: string
                  type:
                    description: |-
                      Type of condition in CamelCase or in foo.example.com/CamelCase.
                      Many .condition.type values are consistent across resources like Available, but because arbitrary conditions
                      can be useful (see .node.status.conditions), the ability to deconflict is important.
                    type: string
                required:
                - lastTransitionTime
                - status
                - type
                type: object
              type: array
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
