apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
    managed-by: tmc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        tmc.kcp.io/cluster-placement: "east,west"
    spec:
      containers:
      - name: hello-world
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: MESSAGE
          value: "Hello from TMC!"
        - name: CLUSTER_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: setup
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          cat > /html/index.html << 'HTML'
          <!DOCTYPE html>
          <html>
          <head>
              <title>TMC Hello World</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 40px; }
                  .header { color: #2c3e50; }
                  .info { background: #ecf0f1; padding: 10px; border-radius: 5px; }
                  .cluster { color: #3498db; font-weight: bold; }
              </style>
          </head>
          <body>
              <h1 class="header">🚀 Hello from TMC!</h1>
              <div class="info">
                  <p><strong>Message:</strong> ${MESSAGE}</p>
                  <p><strong>Cluster:</strong> <span class="cluster">${CLUSTER_NAME}</span></p>
                  <p><strong>Pod:</strong> $(hostname)</p>
                  <p><strong>Time:</strong> $(date)</p>
                  <p><strong>TMC Features:</strong> Multi-cluster deployment, Resource aggregation, Health monitoring</p>
              </div>
              <h2>TMC Capabilities Demonstrated:</h2>
              <ul>
                  <li>✅ Cross-cluster workload distribution</li>
                  <li>✅ Unified resource management</li>
                  <li>✅ Automated health monitoring</li>
                  <li>✅ Intelligent recovery strategies</li>
                  <li>✅ Virtual workspace abstractions</li>
              </ul>
          </body>
          </html>
          HTML
        volumeMounts:
        - name: html
          mountPath: /html
      volumes:
      - name: html
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-config
  labels:
    app: hello-world
    tmc.kcp.io/project: "true"
data:
  message: "Hello from TMC Virtual Workspace!"
  environment: "tutorial"
  features: |
    - cross-cluster aggregation
    - resource projection
    - health monitoring
    - automated recovery
  config.json: |
    {
      "tmc": {
        "enabled": true,
        "features": {
          "aggregation": true,
          "projection": true,
          "recovery": true,
          "health_monitoring": true
        },
        "clusters": ["east", "west"],
        "placement_policy": "multi-cluster"
      }
    }
