kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: policy-dev
networking:
  apiServerPort: 40444
  apiServerAddress: "127.0.0.1"
nodes:
- role: control-plane
  image: kindest/node:v1.27.3
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "region=us-west-1,cluster=dev,demo=policy-enforcement,environment=development,policy-tier=relaxed"
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        enable-admission-plugins: "NodeRestriction,ResourceQuota"
- role: worker
  image: kindest/node:v1.27.3
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "region=us-west-1,cluster=dev,demo=policy-enforcement,environment=development,policy-tier=relaxed"