apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-workload.fullname" . }}
  labels:
    {{- include "demo-workload.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-workload.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-workload.selectorLabels" . | nindent 8 }}
        demo: {{ .Values.demo }}
        cluster: {{ .Values.cluster }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.cluster }}
            - name: MESSAGE
              value: {{ .Values.message }}
            - name: TMC_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
