//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	intstr "k8s.io/apimachinery/pkg/util/intstr"

	conditionsv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/third_party/conditions/apis/conditions/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregatedField) DeepCopyInto(out *AggregatedField) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregatedField.
func (in *AggregatedField) DeepCopy() *AggregatedField {
	if in == nil {
		return nil
	}
	out := new(AggregatedField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregatedLocationStatus) DeepCopyInto(out *AggregatedLocationStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	in.ExtractedFields.DeepCopyInto(&out.ExtractedFields)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregatedLocationStatus.
func (in *AggregatedLocationStatus) DeepCopy() *AggregatedLocationStatus {
	if in == nil {
		return nil
	}
	out := new(AggregatedLocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AggregationPolicy) DeepCopyInto(out *AggregationPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AggregationPolicy.
func (in *AggregationPolicy) DeepCopy() *AggregationPolicy {
	if in == nil {
		return nil
	}
	out := new(AggregationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionRequirement) DeepCopyInto(out *ConditionRequirement) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionRequirement.
func (in *ConditionRequirement) DeepCopy() *ConditionRequirement {
	if in == nil {
		return nil
	}
	out := new(ConditionRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthPolicy) DeepCopyInto(out *HealthPolicy) {
	*out = *in
	if in.HealthyConditions != nil {
		in, out := &in.HealthyConditions, &out.HealthyConditions
		*out = make([]ConditionRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnhealthyConditions != nil {
		in, out := &in.UnhealthyConditions, &out.UnhealthyConditions
		*out = make([]ConditionRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinHealthyReplicas != nil {
		in, out := &in.MinHealthyReplicas, &out.MinHealthyReplicas
		*out = new(intstr.IntOrString)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthPolicy.
func (in *HealthPolicy) DeepCopy() *HealthPolicy {
	if in == nil {
		return nil
	}
	out := new(HealthPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusFieldSelector) DeepCopyInto(out *StatusFieldSelector) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusFieldSelector.
func (in *StatusFieldSelector) DeepCopy() *StatusFieldSelector {
	if in == nil {
		return nil
	}
	out := new(StatusFieldSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadReference) DeepCopyInto(out *WorkloadReference) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadReference.
func (in *WorkloadReference) DeepCopy() *WorkloadReference {
	if in == nil {
		return nil
	}
	out := new(WorkloadReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStatusAggregation) DeepCopyInto(out *WorkloadStatusAggregation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatusAggregation.
func (in *WorkloadStatusAggregation) DeepCopy() *WorkloadStatusAggregation {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatusAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadStatusAggregation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStatusAggregationList) DeepCopyInto(out *WorkloadStatusAggregationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadStatusAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatusAggregationList.
func (in *WorkloadStatusAggregationList) DeepCopy() *WorkloadStatusAggregationList {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatusAggregationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadStatusAggregationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStatusAggregationSpec) DeepCopyInto(out *WorkloadStatusAggregationSpec) {
	*out = *in
	out.WorkloadRef = in.WorkloadRef
	if in.StatusFields != nil {
		in, out := &in.StatusFields, &out.StatusFields
		*out = make([]StatusFieldSelector, len(*in))
		copy(*out, *in)
	}
	if in.AggregationPolicy != nil {
		in, out := &in.AggregationPolicy, &out.AggregationPolicy
		*out = new(AggregationPolicy)
		**out = **in
	}
	if in.HealthPolicy != nil {
		in, out := &in.HealthPolicy, &out.HealthPolicy
		*out = new(HealthPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.UpdateFrequency != nil {
		in, out := &in.UpdateFrequency, &out.UpdateFrequency
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatusAggregationSpec.
func (in *WorkloadStatusAggregationSpec) DeepCopy() *WorkloadStatusAggregationSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatusAggregationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadStatusAggregationStatus) DeepCopyInto(out *WorkloadStatusAggregationStatus) {
	*out = *in
	if in.LocationStatuses != nil {
		in, out := &in.LocationStatuses, &out.LocationStatuses
		*out = make([]AggregatedLocationStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AggregatedFields != nil {
		in, out := &in.AggregatedFields, &out.AggregatedFields
		*out = make([]AggregatedField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAggregationTime != nil {
		in, out := &in.LastAggregationTime, &out.LastAggregationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(conditionsv1alpha1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadStatusAggregationStatus.
func (in *WorkloadStatusAggregationStatus) DeepCopy() *WorkloadStatusAggregationStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadStatusAggregationStatus)
	in.DeepCopyInto(out)
	return out
}
