/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	tmcv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/tmc/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/kcp/sdk/client/applyconfiguration/tmc/v1alpha1"
	typedkcptmcv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/cluster/typed/tmc/v1alpha1"
	typedtmcv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/tmc/v1alpha1"
	"github.com/kcp-dev/logicalcluster/v3"
)

// clusterRegistrationClusterClient implements ClusterRegistrationClusterInterface
type clusterRegistrationClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*tmcv1alpha1.ClusterRegistration, *tmcv1alpha1.ClusterRegistrationList]
	Fake *kcptesting.Fake
}

func newFakeClusterRegistrationClusterClient(fake *TmcV1alpha1ClusterClient) typedkcptmcv1alpha1.ClusterRegistrationClusterInterface {
	return &clusterRegistrationClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*tmcv1alpha1.ClusterRegistration, *tmcv1alpha1.ClusterRegistrationList](
			fake.Fake,
			tmcv1alpha1.SchemeGroupVersion.WithResource("clusterregistrations"),
			tmcv1alpha1.SchemeGroupVersion.WithKind("ClusterRegistration"),
			func() *tmcv1alpha1.ClusterRegistration { return &tmcv1alpha1.ClusterRegistration{} },
			func() *tmcv1alpha1.ClusterRegistrationList { return &tmcv1alpha1.ClusterRegistrationList{} },
			func(dst, src *tmcv1alpha1.ClusterRegistrationList) { dst.ListMeta = src.ListMeta },
			func(list *tmcv1alpha1.ClusterRegistrationList) []*tmcv1alpha1.ClusterRegistration {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *tmcv1alpha1.ClusterRegistrationList, items []*tmcv1alpha1.ClusterRegistration) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *clusterRegistrationClusterClient) Cluster(cluster logicalcluster.Path) typedtmcv1alpha1.ClusterRegistrationInterface {
	return newFakeClusterRegistrationClient(c.Fake, cluster)
}

// clusterRegistrationScopedClient implements ClusterRegistrationInterface
type clusterRegistrationScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*tmcv1alpha1.ClusterRegistration, *tmcv1alpha1.ClusterRegistrationList, *kcpv1alpha1.ClusterRegistrationApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeClusterRegistrationClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedtmcv1alpha1.ClusterRegistrationInterface {
	return &clusterRegistrationScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*tmcv1alpha1.ClusterRegistration, *tmcv1alpha1.ClusterRegistrationList, *kcpv1alpha1.ClusterRegistrationApplyConfiguration](
			fake,
			clusterPath,
			"",
			tmcv1alpha1.SchemeGroupVersion.WithResource("clusterregistrations"),
			tmcv1alpha1.SchemeGroupVersion.WithKind("ClusterRegistration"),
			func() *tmcv1alpha1.ClusterRegistration { return &tmcv1alpha1.ClusterRegistration{} },
			func() *tmcv1alpha1.ClusterRegistrationList { return &tmcv1alpha1.ClusterRegistrationList{} },
			func(dst, src *tmcv1alpha1.ClusterRegistrationList) { dst.ListMeta = src.ListMeta },
			func(list *tmcv1alpha1.ClusterRegistrationList) []*tmcv1alpha1.ClusterRegistration {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *tmcv1alpha1.ClusterRegistrationList, items []*tmcv1alpha1.ClusterRegistration) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
