/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	kcptmcv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/cluster/typed/tmc/v1alpha1"
	tmcv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/tmc/v1alpha1"
	"github.com/kcp-dev/logicalcluster/v3"
	rest "k8s.io/client-go/rest"
)

var _ kcptmcv1alpha1.TmcV1alpha1ClusterInterface = (*TmcV1alpha1ClusterClient)(nil)

type TmcV1alpha1ClusterClient struct {
	*kcptesting.Fake
}

func (c *TmcV1alpha1ClusterClient) Cluster(clusterPath logicalcluster.Path) tmcv1alpha1.TmcV1alpha1Interface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}
	return &TmcV1alpha1Client{Fake: c.Fake, ClusterPath: clusterPath}
}

func (c *TmcV1alpha1ClusterClient) ClusterRegistrations() kcptmcv1alpha1.ClusterRegistrationClusterInterface {
	return newFakeClusterRegistrationClusterClient(c)
}

func (c *TmcV1alpha1ClusterClient) WorkloadPlacements() kcptmcv1alpha1.WorkloadPlacementClusterInterface {
	return newFakeWorkloadPlacementClusterClient(c)
}

type TmcV1alpha1Client struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (c *TmcV1alpha1Client) ClusterRegistrations() tmcv1alpha1.ClusterRegistrationInterface {
	return newFakeClusterRegistrationClient(c.Fake, c.ClusterPath)
}

func (c *TmcV1alpha1Client) WorkloadPlacements(namespace string) tmcv1alpha1.WorkloadPlacementInterface {
	return newFakeWorkloadPlacementClient(c.Fake, namespace, c.ClusterPath)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *TmcV1alpha1Client) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
