/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	kcptmcv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/tmc/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/tmc/v1alpha1"
	"github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
)

// ClusterRegistrationsClusterGetter has a method to return a ClusterRegistrationClusterInterface.
// A group's cluster client should implement this interface.
type ClusterRegistrationsClusterGetter interface {
	ClusterRegistrations() ClusterRegistrationClusterInterface
}

// ClusterRegistrationClusterInterface can operate on ClusterRegistrations across all clusters,
// or scope down to one cluster and return a kcpv1alpha1.ClusterRegistrationInterface.
type ClusterRegistrationClusterInterface interface {
	Cluster(logicalcluster.Path) kcpv1alpha1.ClusterRegistrationInterface
	List(ctx context.Context, opts v1.ListOptions) (*kcptmcv1alpha1.ClusterRegistrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	ClusterRegistrationClusterExpansion
}

type clusterRegistrationsClusterInterface struct {
	clientCache kcpclient.Cache[*kcpv1alpha1.TmcV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *clusterRegistrationsClusterInterface) Cluster(clusterPath logicalcluster.Path) kcpv1alpha1.ClusterRegistrationInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).ClusterRegistrations()
}

// List returns the entire collection of all ClusterRegistrations across all clusters.
func (c *clusterRegistrationsClusterInterface) List(ctx context.Context, opts v1.ListOptions) (*kcptmcv1alpha1.ClusterRegistrationList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterRegistrations().List(ctx, opts)
}

// Watch begins to watch all ClusterRegistrations across all clusters.
func (c *clusterRegistrationsClusterInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterRegistrations().Watch(ctx, opts)
}
