/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// AggregatedFieldApplyConfiguration represents a declarative configuration of the AggregatedField type for use
// with apply.
type AggregatedFieldApplyConfiguration struct {
	Name        *string               `json:"name,omitempty"`
	DisplayName *string               `json:"displayName,omitempty"`
	Value       *runtime.RawExtension `json:"value,omitempty"`
	Sources     []string              `json:"sources,omitempty"`
}

// AggregatedFieldApplyConfiguration constructs a declarative configuration of the AggregatedField type for use with
// apply.
func AggregatedField() *AggregatedFieldApplyConfiguration {
	return &AggregatedFieldApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *AggregatedFieldApplyConfiguration) WithName(value string) *AggregatedFieldApplyConfiguration {
	b.Name = &value
	return b
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *AggregatedFieldApplyConfiguration) WithDisplayName(value string) *AggregatedFieldApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *AggregatedFieldApplyConfiguration) WithValue(value runtime.RawExtension) *AggregatedFieldApplyConfiguration {
	b.Value = &value
	return b
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *AggregatedFieldApplyConfiguration) WithSources(values ...string) *AggregatedFieldApplyConfiguration {
	for i := range values {
		b.Sources = append(b.Sources, values[i])
	}
	return b
}
