/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ConditionRequirementApplyConfiguration represents a declarative configuration of the ConditionRequirement type for use
// with apply.
type ConditionRequirementApplyConfiguration struct {
	Type    *string             `json:"type,omitempty"`
	Status  *v1.ConditionStatus `json:"status,omitempty"`
	Reasons []string            `json:"reasons,omitempty"`
}

// ConditionRequirementApplyConfiguration constructs a declarative configuration of the ConditionRequirement type for use with
// apply.
func ConditionRequirement() *ConditionRequirementApplyConfiguration {
	return &ConditionRequirementApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ConditionRequirementApplyConfiguration) WithType(value string) *ConditionRequirementApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ConditionRequirementApplyConfiguration) WithStatus(value v1.ConditionStatus) *ConditionRequirementApplyConfiguration {
	b.Status = &value
	return b
}

// WithReasons adds the given value to the Reasons field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Reasons field.
func (b *ConditionRequirementApplyConfiguration) WithReasons(values ...string) *ConditionRequirementApplyConfiguration {
	for i := range values {
		b.Reasons = append(b.Reasons, values[i])
	}
	return b
}
