# Shared Multi-Tenant Cluster Configuration
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tenant-shared
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 41444
  disableDefaultCNI: false
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.97.0.0/12"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true,tenant-tier=shared"
        authorization-mode: "Webhook"
    ---
    kind: KubeletConfiguration
    serverTLSBootstrap: true
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        runtime-config: "api/all=true"
        feature-gates: "EphemeralContainers=true"
        audit-log-path: "/var/log/audit.log"
        audit-policy-file: "/etc/kubernetes/audit-policy.yaml"
    controllerManager:
      extraArgs:
        feature-gates: "EphemeralContainers=true"
        bind-address: "0.0.0.0"
    scheduler:
      extraArgs:
        feature-gates: "EphemeralContainers=true"
        bind-address: "0.0.0.0"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30881
    protocol: TCP
  - containerPort: 30443
    hostPort: 30884
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "tenant-tier=shared,workload-type=multi-tenant"