/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterRegistrationClusterListerExpansion allows custom methods to be added to
// ClusterRegistrationClusterLister.
type ClusterRegistrationClusterListerExpansion interface{}

// ClusterRegistrationListerExpansion allows custom methods to be added to
// ClusterRegistrationLister.
type ClusterRegistrationListerExpansion interface{}

// WorkloadPlacementClusterListerExpansion allows custom methods to be added to
// WorkloadPlacementClusterLister.
type WorkloadPlacementClusterListerExpansion interface{}

// WorkloadPlacementListerExpansion allows custom methods to be added to
// WorkloadPlacementLister.
type WorkloadPlacementListerExpansion interface{}

// WorkloadPlacementNamespaceListerExpansion allows custom methods to be added to
// WorkloadPlacementNamespaceLister.
type WorkloadPlacementNamespaceListerExpansion interface{}
