/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-informer-gen. DO NOT EDIT.

package v1alpha1

import (
	kcpinternalinterfaces "github.com/kcp-dev/kcp/sdk/client/informers/externalversions/internalinterfaces"
)

type ClusterInterface interface {
	// WorkloadStatusAggregations returns a WorkloadStatusAggregationClusterInformer.
	WorkloadStatusAggregations() WorkloadStatusAggregationClusterInformer
}

type version struct {
	factory          kcpinternalinterfaces.SharedInformerFactory
	tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f kcpinternalinterfaces.SharedInformerFactory, tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc) ClusterInterface {
	return &version{factory: f, tweakListOptions: tweakListOptions}
}

// WorkloadStatusAggregations returns a WorkloadStatusAggregationClusterInformer.
func (v *version) WorkloadStatusAggregations() WorkloadStatusAggregationClusterInformer {
	return &workloadStatusAggregationClusterInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

type Interface interface {
	// WorkloadStatusAggregations returns a WorkloadStatusAggregationInformer.
	WorkloadStatusAggregations() WorkloadStatusAggregationInformer
}

type scopedVersion struct {
	factory          kcpinternalinterfaces.SharedScopedInformerFactory
	tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc
	namespace        string
}

// New returns a new Interface.
func NewScoped(f kcpinternalinterfaces.SharedScopedInformerFactory, namespace string, tweakListOptions kcpinternalinterfaces.TweakListOptionsFunc) Interface {
	return &scopedVersion{factory: f, tweakListOptions: tweakListOptions}
}

// WorkloadStatusAggregations returns a WorkloadStatusAggregationInformer.
func (v *scopedVersion) WorkloadStatusAggregations() WorkloadStatusAggregationInformer {
	return &workloadStatusAggregationScopedInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
