kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tmc-east
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "region=east,cluster-role=workload"
