kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: tmc-kcp
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "region=control,cluster-role=kcp-host"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
