apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-kcp-tmc.fullname" . }}
  labels:
    {{- include "demo-kcp-tmc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "demo-kcp-tmc.selectorLabels" . | nindent 4 }}
