/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	kcpv1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tmc/v1alpha1"
	kcptmcv1alpha1 "github.com/kcp-dev/kcp/pkg/client/tmc/clientset/versioned/typed/tmc/v1alpha1"
	"github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	watch "k8s.io/apimachinery/pkg/watch"
)

// WorkloadPlacementsClusterGetter has a method to return a WorkloadPlacementClusterInterface.
// A group's cluster client should implement this interface.
type WorkloadPlacementsClusterGetter interface {
	WorkloadPlacements() WorkloadPlacementClusterInterface
}

// WorkloadPlacementClusterInterface can operate on WorkloadPlacements across all clusters,
// or scope down to one cluster and return a WorkloadPlacementsNamespacer.
type WorkloadPlacementClusterInterface interface {
	Cluster(logicalcluster.Path) WorkloadPlacementsNamespacer
	List(ctx context.Context, opts v1.ListOptions) (*kcpv1alpha1.WorkloadPlacementList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	WorkloadPlacementClusterExpansion
}

type workloadPlacementsClusterInterface struct {
	clientCache kcpclient.Cache[*kcptmcv1alpha1.TmcV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *workloadPlacementsClusterInterface) Cluster(clusterPath logicalcluster.Path) WorkloadPlacementsNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &workloadPlacementsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all WorkloadPlacements across all clusters.
func (c *workloadPlacementsClusterInterface) List(ctx context.Context, opts v1.ListOptions) (*kcpv1alpha1.WorkloadPlacementList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).WorkloadPlacements(v1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all WorkloadPlacements across all clusters.
func (c *workloadPlacementsClusterInterface) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).WorkloadPlacements(v1.NamespaceAll).Watch(ctx, opts)
}

// WorkloadPlacementsNamespacer can scope to objects within a namespace, returning a kcptmcv1alpha1.WorkloadPlacementInterface.
type WorkloadPlacementsNamespacer interface {
	Namespace(string) kcptmcv1alpha1.WorkloadPlacementInterface
}

type workloadPlacementsNamespacer struct {
	clientCache kcpclient.Cache[*kcptmcv1alpha1.TmcV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *workloadPlacementsNamespacer) Namespace(namespace string) kcptmcv1alpha1.WorkloadPlacementInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).WorkloadPlacements(namespace)
}
