/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterRegistrationSpecApplyConfiguration represents a declarative configuration of the ClusterRegistrationSpec type for use
// with apply.
type ClusterRegistrationSpecApplyConfiguration struct {
	Location        *string                            `json:"location,omitempty"`
	ClusterEndpoint *ClusterEndpointApplyConfiguration `json:"clusterEndpoint,omitempty"`
	Capacity        *ClusterCapacityApplyConfiguration `json:"capacity,omitempty"`
}

// ClusterRegistrationSpecApplyConfiguration constructs a declarative configuration of the ClusterRegistrationSpec type for use with
// apply.
func ClusterRegistrationSpec() *ClusterRegistrationSpecApplyConfiguration {
	return &ClusterRegistrationSpecApplyConfiguration{}
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *ClusterRegistrationSpecApplyConfiguration) WithLocation(value string) *ClusterRegistrationSpecApplyConfiguration {
	b.Location = &value
	return b
}

// WithClusterEndpoint sets the ClusterEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterEndpoint field is set to the value of the last call.
func (b *ClusterRegistrationSpecApplyConfiguration) WithClusterEndpoint(value *ClusterEndpointApplyConfiguration) *ClusterRegistrationSpecApplyConfiguration {
	b.ClusterEndpoint = value
	return b
}

// WithCapacity sets the Capacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capacity field is set to the value of the last call.
func (b *ClusterRegistrationSpecApplyConfiguration) WithCapacity(value *ClusterCapacityApplyConfiguration) *ClusterRegistrationSpecApplyConfiguration {
	b.Capacity = value
	return b
}
