/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// WorkloadSelectorApplyConfiguration represents a declarative configuration of the WorkloadSelector type for use
// with apply.
type WorkloadSelectorApplyConfiguration struct {
	LabelSelector     *v1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
	WorkloadTypes     []WorkloadTypeApplyConfiguration    `json:"workloadTypes,omitempty"`
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
}

// WorkloadSelectorApplyConfiguration constructs a declarative configuration of the WorkloadSelector type for use with
// apply.
func WorkloadSelector() *WorkloadSelectorApplyConfiguration {
	return &WorkloadSelectorApplyConfiguration{}
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *WorkloadSelectorApplyConfiguration) WithLabelSelector(value *v1.LabelSelectorApplyConfiguration) *WorkloadSelectorApplyConfiguration {
	b.LabelSelector = value
	return b
}

// WithWorkloadTypes adds the given value to the WorkloadTypes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WorkloadTypes field.
func (b *WorkloadSelectorApplyConfiguration) WithWorkloadTypes(values ...*WorkloadTypeApplyConfiguration) *WorkloadSelectorApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWorkloadTypes")
		}
		b.WorkloadTypes = append(b.WorkloadTypes, *values[i])
	}
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *WorkloadSelectorApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *WorkloadSelectorApplyConfiguration {
	b.NamespaceSelector = value
	return b
}
