//go:build !ignore_autogenerated

/*
Copyright  The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	conditionsv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/third_party/conditions/apis/conditions/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompatibleLocation) DeepCopyInto(out *CompatibleLocation) {
	*out = *in
	if in.SupportedVersions != nil {
		in, out := &in.SupportedVersions, &out.SupportedVersions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = make([]LocationConstraint, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompatibleLocation.
func (in *CompatibleLocation) DeepCopy() *CompatibleLocation {
	if in == nil {
		return nil
	}
	out := new(CompatibleLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FieldRequirement) DeepCopyInto(out *FieldRequirement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FieldRequirement.
func (in *FieldRequirement) DeepCopy() *FieldRequirement {
	if in == nil {
		return nil
	}
	out := new(FieldRequirement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupVersionSpec) DeepCopyInto(out *GroupVersionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupVersionSpec.
func (in *GroupVersionSpec) DeepCopy() *GroupVersionSpec {
	if in == nil {
		return nil
	}
	out := new(GroupVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncompatibleLocation) DeepCopyInto(out *IncompatibleLocation) {
	*out = *in
	if in.MissingFields != nil {
		in, out := &in.MissingFields, &out.MissingFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncompatibleLocation.
func (in *IncompatibleLocation) DeepCopy() *IncompatibleLocation {
	if in == nil {
		return nil
	}
	out := new(IncompatibleLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocationConstraint) DeepCopyInto(out *LocationConstraint) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocationConstraint.
func (in *LocationConstraint) DeepCopy() *LocationConstraint {
	if in == nil {
		return nil
	}
	out := new(LocationConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NegotiatedAPIResource) DeepCopyInto(out *NegotiatedAPIResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NegotiatedAPIResource.
func (in *NegotiatedAPIResource) DeepCopy() *NegotiatedAPIResource {
	if in == nil {
		return nil
	}
	out := new(NegotiatedAPIResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NegotiatedAPIResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NegotiatedAPIResourceList) DeepCopyInto(out *NegotiatedAPIResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NegotiatedAPIResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NegotiatedAPIResourceList.
func (in *NegotiatedAPIResourceList) DeepCopy() *NegotiatedAPIResourceList {
	if in == nil {
		return nil
	}
	out := new(NegotiatedAPIResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NegotiatedAPIResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NegotiatedAPIResourceSpec) DeepCopyInto(out *NegotiatedAPIResourceSpec) {
	*out = *in
	out.GroupVersion = in.GroupVersion
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]ResourceNegotiation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CommonSchema != nil {
		in, out := &in.CommonSchema, &out.CommonSchema
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NegotiatedAPIResourceSpec.
func (in *NegotiatedAPIResourceSpec) DeepCopy() *NegotiatedAPIResourceSpec {
	if in == nil {
		return nil
	}
	out := new(NegotiatedAPIResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NegotiatedAPIResourceStatus) DeepCopyInto(out *NegotiatedAPIResourceStatus) {
	*out = *in
	if in.CompatibleLocations != nil {
		in, out := &in.CompatibleLocations, &out.CompatibleLocations
		*out = make([]CompatibleLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IncompatibleLocations != nil {
		in, out := &in.IncompatibleLocations, &out.IncompatibleLocations
		*out = make([]IncompatibleLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastNegotiationTime != nil {
		in, out := &in.LastNegotiationTime, &out.LastNegotiationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(conditionsv1alpha1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NegotiatedAPIResourceStatus.
func (in *NegotiatedAPIResourceStatus) DeepCopy() *NegotiatedAPIResourceStatus {
	if in == nil {
		return nil
	}
	out := new(NegotiatedAPIResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceNegotiation) DeepCopyInto(out *ResourceNegotiation) {
	*out = *in
	if in.Subresources != nil {
		in, out := &in.Subresources, &out.Subresources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequiredFields != nil {
		in, out := &in.RequiredFields, &out.RequiredFields
		*out = make([]FieldRequirement, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceNegotiation.
func (in *ResourceNegotiation) DeepCopy() *ResourceNegotiation {
	if in == nil {
		return nil
	}
	out := new(ResourceNegotiation)
	in.DeepCopyInto(out)
	return out
}
