/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	workloadv1alpha1 "github.com/kcp-dev/kcp/sdk/apis/workload/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/kcp/sdk/client/applyconfiguration/workload/v1alpha1"
	typedkcpworkloadv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/cluster/typed/workload/v1alpha1"
	typedworkloadv1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/workload/v1alpha1"
)

// workloadStatusAggregationClusterClient implements WorkloadStatusAggregationClusterInterface
type workloadStatusAggregationClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*workloadv1alpha1.WorkloadStatusAggregation, *workloadv1alpha1.WorkloadStatusAggregationList]
	Fake *kcptesting.Fake
}

func newFakeWorkloadStatusAggregationClusterClient(fake *WorkloadV1alpha1ClusterClient) typedkcpworkloadv1alpha1.WorkloadStatusAggregationClusterInterface {
	return &workloadStatusAggregationClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*workloadv1alpha1.WorkloadStatusAggregation, *workloadv1alpha1.WorkloadStatusAggregationList](
			fake.Fake,
			workloadv1alpha1.SchemeGroupVersion.WithResource("workloadstatusaggregations"),
			workloadv1alpha1.SchemeGroupVersion.WithKind("WorkloadStatusAggregation"),
			func() *workloadv1alpha1.WorkloadStatusAggregation {
				return &workloadv1alpha1.WorkloadStatusAggregation{}
			},
			func() *workloadv1alpha1.WorkloadStatusAggregationList {
				return &workloadv1alpha1.WorkloadStatusAggregationList{}
			},
			func(dst, src *workloadv1alpha1.WorkloadStatusAggregationList) { dst.ListMeta = src.ListMeta },
			func(list *workloadv1alpha1.WorkloadStatusAggregationList) []*workloadv1alpha1.WorkloadStatusAggregation {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *workloadv1alpha1.WorkloadStatusAggregationList, items []*workloadv1alpha1.WorkloadStatusAggregation) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *workloadStatusAggregationClusterClient) Cluster(cluster logicalcluster.Path) typedworkloadv1alpha1.WorkloadStatusAggregationInterface {
	return newFakeWorkloadStatusAggregationClient(c.Fake, cluster)
}

// workloadStatusAggregationScopedClient implements WorkloadStatusAggregationInterface
type workloadStatusAggregationScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*workloadv1alpha1.WorkloadStatusAggregation, *workloadv1alpha1.WorkloadStatusAggregationList, *kcpv1alpha1.WorkloadStatusAggregationApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeWorkloadStatusAggregationClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedworkloadv1alpha1.WorkloadStatusAggregationInterface {
	return &workloadStatusAggregationScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*workloadv1alpha1.WorkloadStatusAggregation, *workloadv1alpha1.WorkloadStatusAggregationList, *kcpv1alpha1.WorkloadStatusAggregationApplyConfiguration](
			fake,
			clusterPath,
			"",
			workloadv1alpha1.SchemeGroupVersion.WithResource("workloadstatusaggregations"),
			workloadv1alpha1.SchemeGroupVersion.WithKind("WorkloadStatusAggregation"),
			func() *workloadv1alpha1.WorkloadStatusAggregation {
				return &workloadv1alpha1.WorkloadStatusAggregation{}
			},
			func() *workloadv1alpha1.WorkloadStatusAggregationList {
				return &workloadv1alpha1.WorkloadStatusAggregationList{}
			},
			func(dst, src *workloadv1alpha1.WorkloadStatusAggregationList) { dst.ListMeta = src.ListMeta },
			func(list *workloadv1alpha1.WorkloadStatusAggregationList) []*workloadv1alpha1.WorkloadStatusAggregation {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *workloadv1alpha1.WorkloadStatusAggregationList, items []*workloadv1alpha1.WorkloadStatusAggregation) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
