kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kcp-host
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "region=control"
  extraPortMappings:
  - containerPort: 6443
    hostPort: 16443
    protocol: TCP
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 16443
