/*
Copyright 2024 The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated typed clients.
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/serializer"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"

	v1alpha1 "github.com/kcp-dev/kcp/pkg/apis/tmc/v1alpha1"
)

var Scheme = runtime.NewScheme()
var ParameterCodec = serializer.NewCodecFactory(Scheme).LegacyCodec(v1alpha1.SchemeGroupVersion)

func init() {
	utilruntime.Must(v1alpha1.AddToScheme(Scheme))
}