replicaCount: 1

image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 6443

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

demo: "helm-deployment"
