replicaCount: 3

image:
  repository: nginx
  pullPolicy: Always
  tag: "latest"

nameOverride: "helm-west"
fullnameOverride: "helm-west"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

demo: "helm-deployment"
cluster: "west"
message: "Hello from West Cluster via Helm!"
