/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	apiresourcev1alpha1 "github.com/kcp-dev/kcp/sdk/apis/apiresource/v1alpha1"
	kcpv1alpha1 "github.com/kcp-dev/kcp/sdk/client/applyconfiguration/apiresource/v1alpha1"
	typedkcpapiresourcev1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/cluster/typed/apiresource/v1alpha1"
	typedapiresourcev1alpha1 "github.com/kcp-dev/kcp/sdk/client/clientset/versioned/typed/apiresource/v1alpha1"
)

// negotiatedAPIResourceClusterClient implements NegotiatedAPIResourceClusterInterface
type negotiatedAPIResourceClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*apiresourcev1alpha1.NegotiatedAPIResource, *apiresourcev1alpha1.NegotiatedAPIResourceList]
	Fake *kcptesting.Fake
}

func newFakeNegotiatedAPIResourceClusterClient(fake *ApiresourceV1alpha1ClusterClient) typedkcpapiresourcev1alpha1.NegotiatedAPIResourceClusterInterface {
	return &negotiatedAPIResourceClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*apiresourcev1alpha1.NegotiatedAPIResource, *apiresourcev1alpha1.NegotiatedAPIResourceList](
			fake.Fake,
			apiresourcev1alpha1.SchemeGroupVersion.WithResource("negotiatedapiresources"),
			apiresourcev1alpha1.SchemeGroupVersion.WithKind("NegotiatedAPIResource"),
			func() *apiresourcev1alpha1.NegotiatedAPIResource { return &apiresourcev1alpha1.NegotiatedAPIResource{} },
			func() *apiresourcev1alpha1.NegotiatedAPIResourceList {
				return &apiresourcev1alpha1.NegotiatedAPIResourceList{}
			},
			func(dst, src *apiresourcev1alpha1.NegotiatedAPIResourceList) { dst.ListMeta = src.ListMeta },
			func(list *apiresourcev1alpha1.NegotiatedAPIResourceList) []*apiresourcev1alpha1.NegotiatedAPIResource {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *apiresourcev1alpha1.NegotiatedAPIResourceList, items []*apiresourcev1alpha1.NegotiatedAPIResource) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *negotiatedAPIResourceClusterClient) Cluster(cluster logicalcluster.Path) typedapiresourcev1alpha1.NegotiatedAPIResourceInterface {
	return newFakeNegotiatedAPIResourceClient(c.Fake, cluster)
}

// negotiatedAPIResourceScopedClient implements NegotiatedAPIResourceInterface
type negotiatedAPIResourceScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*apiresourcev1alpha1.NegotiatedAPIResource, *apiresourcev1alpha1.NegotiatedAPIResourceList, *kcpv1alpha1.NegotiatedAPIResourceApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeNegotiatedAPIResourceClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedapiresourcev1alpha1.NegotiatedAPIResourceInterface {
	return &negotiatedAPIResourceScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*apiresourcev1alpha1.NegotiatedAPIResource, *apiresourcev1alpha1.NegotiatedAPIResourceList, *kcpv1alpha1.NegotiatedAPIResourceApplyConfiguration](
			fake,
			clusterPath,
			"",
			apiresourcev1alpha1.SchemeGroupVersion.WithResource("negotiatedapiresources"),
			apiresourcev1alpha1.SchemeGroupVersion.WithKind("NegotiatedAPIResource"),
			func() *apiresourcev1alpha1.NegotiatedAPIResource { return &apiresourcev1alpha1.NegotiatedAPIResource{} },
			func() *apiresourcev1alpha1.NegotiatedAPIResourceList {
				return &apiresourcev1alpha1.NegotiatedAPIResourceList{}
			},
			func(dst, src *apiresourcev1alpha1.NegotiatedAPIResourceList) { dst.ListMeta = src.ListMeta },
			func(list *apiresourcev1alpha1.NegotiatedAPIResourceList) []*apiresourcev1alpha1.NegotiatedAPIResource {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *apiresourcev1alpha1.NegotiatedAPIResourceList, items []*apiresourcev1alpha1.NegotiatedAPIResource) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
